wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.10.7
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.7.3
dataset_params:
  desc: null
  value:
    alphabet: '0123456789abcdefghijklmnopqrstuvwxyz,.*# '
    augment_chunk: false
    data_dir: /Users/i23271/Downloads/table/datasets/SciTSR
    device: cpu
    dilate: false
    erode: false
    graph_k: 6
    img_size: 256
    kernel_size: 3
    labeling_sanity: true
    text_encode_len: 15
img_params:
  desc: null
  value:
    device: cpu
    exp: table_recognition
    inc: 3
    ks:
    - 3
    - 3
    - 3
    nif:
    - 64
    - 64
    - 64
    ps:
    - 1
    - 1
    - 1
    - 1
    run: version_1_a
    seed: 1234
    sp:
    - 2
    - 2
    - 2
    ss:
    - 1
    - 1
    - 1
model_base_params:
  desc: null
  value:
    biderectional: false
    div: 16.0
    num_classes: 2
    num_hidden_features: 64
    num_node_features: 8
    num_samples: 10
    num_text_features: 64
    vocab_size: 41
trainer_params:
  desc: null
  value:
    batch_size: 32
    beta1: 0.5
    beta2: 0.999
    device: cuda
    exp: table_structure_recognition
    logging_interval: 20
    lr: 0.001
    lr_cooldonw: 2
    lr_patience: 5
    lr_reduce_factor: 0.5
    lr_schedule_mode: min
    min_lr: 1.0e-05
    num_epochs: 100
    optimizer: adam
    run: version_1_a
    save_interval: 1
    schedule_lr: false
    seed: 1234
    val_iterval: 10
    workers: 0
